version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: authz-postgres
    environment:
      POSTGRES_DB: authz
      POSTGRES_USER: authz_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: authz-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: authz-app
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  pgdata:
